# Generated by Django 2.2.22 on 2021-05-08 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('boxing', 'BOXING'), ('wrestling', 'WRESTLING'), ('sumo', 'SUMO')], default='boxing', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='outline',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(choices=[('TBD', 'TBD'), ('player1', 'player1'), ('player2', 'player2')], default='TBD', max_length=30),
        ),
    ]
