# Generated by Django 2.2.22 on 2021-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='winner',
            field=models.CharField(choices=[('ali', 'モハメド・アリ'), ('inoki', 'ジャイアント猪木')], default='ali', max_length=50),
        ),
    ]
