# Generated by Django 2.2.22 on 2021-05-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_post_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.CharField(choices=[('player1', 'player1'), ('player2', 'player2')], default='ali', max_length=50),
        ),
    ]
