# Generated by Django 2.2.22 on 2021-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20210508_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='match_pk',
            field=models.IntegerField(null=True),
        ),
    ]
