# Generated by Django 2.2.22 on 2021-05-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_post_match_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.CharField(choices=[('player1', 'player1'), ('player2', 'player2')], default='player1', max_length=50),
        ),
    ]
